
DINAR = 'dinar'
GAUSSIAN_NOISE = 'gnl'
ADVERSARIAL_NOISE = 'anl'
DINAR_GAUSSIAN_NOISE = 'dinar_gnl'
DINAR_ADVERSARIAL_NOISE = 'dinar_anl'


# Group setup
DINAR_CONFIG = [DINAR, DINAR_GAUSSIAN_NOISE, DINAR_ADVERSARIAL_NOISE]
ADVERSARIAL_CONFIG = [ADVERSARIAL_NOISE, DINAR_ADVERSARIAL_NOISE]
GAUSSIAN_CONFIG = [GAUSSIAN_NOISE, DINAR_ADVERSARIAL_NOISE]