
PerFL = 'perfl'
GAUSSIAN_NOISE = 'gnl'
ADVERSARIAL_NOISE = 'anl'
PerFL_GAUSSIAN_NOISE = 'perfl_gnl'
PerFL_ADVERSARIAL_NOISE = 'perfl_anl'


# Group setup
PerFL_CONFIG = [PerFL, PerFL_GAUSSIAN_NOISE, PerFL_ADVERSARIAL_NOISE]
ADVERSARIAL_CONFIG = [ADVERSARIAL_NOISE, PerFL_ADVERSARIAL_NOISE]
GAUSSIAN_CONFIG = [GAUSSIAN_NOISE, PerFL_ADVERSARIAL_NOISE]